import Navbar from "@/components/navbar";
import "../public/css/globals.css";

export const metadata = {
  title: "Zack | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
