"use client";

import Navbar from "@/components/navbar";
import "../public/css/globals.css";
import Footer from "./footer";

export const metadata = {
  title: "Zack | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div
          onClick={() => {
            const hamburger = document.querySelector(".hamburger");
            const navMenu = document.querySelector("#nav-menu");
            const bar = document.querySelectorAll(".bar");
            if (!hamburger.classList.contains("max-md:hidden")) {
              bar.forEach((e) => {
                e.classList.remove("ganti");
              });
              navMenu.classList.add("max-md:hidden");
            }
          }}
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
